# Generated by Django 3.2.9 on 2021-12-02 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pothole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pId', models.PositiveIntegerField()),
                ('cameraUrl', models.CharField(max_length=100)),
                ('value', models.FloatField(default=0.0)),
            ],
        ),
    ]
