# Generated by Django 3.2.9 on 2021-12-02 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pothole',
            name='address',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pothole',
            name='cameraUrl',
            field=models.CharField(default='', max_length=100),
        ),
    ]
