# Generated by Django 3.2.9 on 2021-12-02 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20211202_2356'),
    ]

    operations = [
        migrations.AddField(
            model_name='pothole',
            name='latitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='pothole',
            name='longitude',
            field=models.FloatField(default=0.0),
        ),
    ]
