# Generated by Django 3.2.9 on 2021-12-03 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_pothole_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='pothole',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='home'),
        ),
    ]
