# Generated by Django 3.2.9 on 2021-12-03 12:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_pothole_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pothole',
            name='video',
            field=models.FileField(null=True, upload_to='home', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])]),
        ),
    ]
